services:
  db:
    image: mysql
    restart: always
    environment: 
      MYSQL_DATABASE: "db"
      MYSQL_USER: "kamal"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - '3306:3306'
    volumes:
      - mydb:/var/lib/mysql

volumes:
  mydb: